server:
  port: 80
eureka:
  client:
    register-with-eureka: false   #false表示不向注册中心注册服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置eureka server 对外交互地址（单机版）
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
feign:
  hystrix:
    enable: true